# Generated by Django 2.2.1 on 2019-05-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='marca',
            field=models.CharField(default='', max_length=25),
        ),
    ]
